name: astr
channels:
  - pytorch
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch=1.8.1
  - pytorch-scatter
  - numba
  - pip
  - pip:
      - -r requirements.txt
